Bug fix '-f' and enhancement '-r'
lkwg82/strip-docker-image pull request #1
Opened 2016-12-12 13:37 UTC by TerraTech

1. strip-docker-image: Fix bug where multiple '-f' were not appending to $FILES
1. Add -r' option to remove files from final image
1. misc mcedit syntax highlighting fix where it gets confused with multiple quotes in an $() construct

As an aside, can you turn on issues for your fork?  It seems that your fork is the best quality I've seen thus far as the official repo seems to have become neglected.

Also, if you need for me to squash these commits, just let me know.

2016-12-12 13:45 UTC, TerraTech commented
Note: I chose '-r' over '-d' as I've seen in other forks it was being used to specify reading from a Dockerfile.

2016-12-18 22:42 UTC, lkwg82 commented
> As an aside, can you turn on issues for your fork?
of course

2016-12-18 22:45 UTC, lkwg82 commented on bin/strip-docker-image-export
> +		    FILES+=" $(printf "${OPTARG}")"
is this by intention?

2016-12-18 23:29 UTC, lkwg82 commented
plz update the readme.md as well

2016-12-19 07:49 UTC, TerraTech commented on bin/strip-docker-image-export
> +		    FILES+=" $(printf "${OPTARG}")"
Well it was, until you fixed argument handling in: https://github.com/lkwg82/strip-docker-image/commit/fca7cf7faca2488a6496039edaf179ee38109c83

My pull request pre-dated that commit, and I had utilized bash's += operator...

2016-12-19 07:54 UTC, TerraTech commented
Given that all this started with fixing '-f', it snowballed into my adding '-r' as well (for a particular project I was currently working on).  Are you interested in adding 'remove' ability?  I also had updated the readme.me file and added '-r' to it and I'm not sure what else is needed to be added.

2016-12-19 19:27 UTC, lkwg82 commented on bin/strip-docker-image-export
> +		    FILES+=" $(printf "${OPTARG}")"
aah, sry oversaw it.

2016-12-19 19:49 UTC, lkwg82 requested changes
just a test

2016-12-19 19:50 UTC, lkwg82 approved these changes

2016-12-19 20:19 UTC, lkwg82 requested changes
```bash
# strip-docker-image -i ubuntu -t ubuntu-stripped-tar -p tar
/mybin/strip-docker-image-export: line 81: printf: -r: invalid option
printf: usage: printf [-v var] format [arguments]
tar: Removing leading `/' from member names
Sending build context to Docker daemon 3.281 MB
Step 1 : FROM scratch
 ---> 
Step 2 : ADD export /
 ---> fa1999b98b1c
Removing intermediate container 0639cdf49265
Step 3 : CMD /bin/bash
 ---> Running in 2897936655af
 ---> 9c1faca3e887
Removing intermediate container 2897936655af
Successfully built 9c1faca3e887
```
Something went wrong

2016-12-19 23:54 UTC, TerraTech commented
@lkwg82 it is a simple fix to the join() function, however I'm working on rebasing to your latest commits.

2016-12-20 00:37 UTC, TerraTech commented
@lkwg82 I've rebased and force pushed which fixes the errant join assumption and only contains the new _rm_ ability.  I removed the '-f' fix as your commit resolves that issue: https://github.com/lkwg82/strip-docker-image/commit/fca7cf7faca2488a6496039edaf179ee38109c83

2016-12-20 21:59 UTC, lkwg82 approved these changes

2016-12-20 22:00 UTC, merged